version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/node:16 # Node.js environment
    steps:
      - checkout # Check out the code
      - run:
          name: Install Dependencies
          command: npm install # Skip if no dependencies
      - run:
          name: Build the Project
          command: npm run build # Replace with your actual build command
      - run:
          name: Deploy to GitHub Pages
          command: |
            git config --global user.email "circleci@circleci.com"
            git config --global user.name "CircleCI"
            git remote set-url origin https://$GITHUB_TOKEN@github.com/pnsnk2410/frontpage_repo.git
            npm install -g gh-pages
            gh-pages -d dist # Replace 'dist' with your build output folder

workflows:
  version: 2
  deploy_site:
    jobs:
      - deploy
